### ISSUE TITLE
驱动与dts匹配

### ISSUE THREAD

**Issue by diaosi-xia** [benfounder/Hi3559AV100_CAN#1]
大佬，驱动匹配是根据dts的compatible属性来匹配的，但是驱动代码里CONFIG_OF这个宏并没有定义，驱动是如何匹配到dts的呢？dts的 interrupts = <0 201 4>;0  201  4 从哪获取到，海思手册里没看到中断号这些，谢谢

**Comment by diaosi-xia** [comment]
static struct platform_driver hisi_can_driver = { .probe = hisi_can_probe,
     .remove = hisi_can_remove,
     .driver = { .name = "hisi_can",
         .of_match_table = of_match_ptr(hisi_can_dt_ids), },
     .id_table = hisi_can_id_table, };
如果是按id_table来匹配的，不是匹配dts的compatible属性， 那怎么知道是can几呢？

**Comment by benfounder** [comment]
dts里面有的都会匹配上啊，所以3个can都驱动了。

201 根据dts里原有设备的中断号，推断一下。

**Comment by diaosi-xia** [comment]
大佬，我没明白啊，
疑问1：Hi3559A╱C V100 ultra-HD Mobile Camera SoC 用户指南手册里中断源表格那章节，312页，can 0 是221  can1 是222.跟你dts写的对不上啊。
疑问2：你说得匹配上是dts 的compatible属性为compatible = "hisilicon,hisi-can",驱动代码里hisi_can_dt_ids定义的compatible = "hisilicon,hisi-can",两个一样就匹配上了。其实现在kernel版本里CONFIG_OF这个宏已经没定义了。

**Comment by benfounder** [comment]
疑问1: 你看看DTS上其他设备的中断号，然后和spec上号比对一下，会发现规律的。
疑问2:只要匹配"hisi-can"就可以了

**Comment by diaosi-xia** [comment]
非常感谢大佬，应用层如何对can进行测试呢

**Comment by diaosi-xia** [comment]
你好，我调试can过程中，执行candump命令，提示&nbsp;Address family not supported by protocol family.，是内核配置有问题吗，比如有模块未加载到。还有因为协议哪里对不上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"benfounder"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 下午4:20
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<Hi3559AV100_CAN@noreply.github.com&gt;;
抄送:&nbsp;"夏接建"<595284218@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)




Closed #1.

**Comment by diaosi-xia** [comment]
内核了配置了下，没有报这个错了。但是现在cansend命令发送数据后就打印&nbsp;interface=can1&nbsp;&nbsp;family=29,type=3,protol=1,然后是write&nbsp;&nbsp;network&nbsp;is&nbsp;down.&nbsp;。我用示波器量没有数据波形，就是1.8的高电平，提示网络是关闭的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"木林森"<595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月26日(星期三) 下午5:52
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



你好，我调试can过程中，执行candump命令，提示&nbsp;Address family not supported by protocol family.，是内核配置有问题吗，比如有模块未加载到。还有因为协议哪里对不上




------------------ 原始邮件 ------------------
发件人:&nbsp;"benfounder"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 下午4:20
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<Hi3559AV100_CAN@noreply.github.com&gt;;
抄送:&nbsp;"夏接建"<595284218@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)




Closed #1.

**Comment by diaosi-xia** [comment]
can 收发数据都正常了，是主板电路有点问题，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"木林森"<595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月27日(星期四) 下午4:00
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



内核了配置了下，没有报这个错了。但是现在cansend命令发送数据后就打印 interface=can1&nbsp; family=29,type=3,protol=1,然后是write&nbsp; network is down. 。我用示波器量没有数据波形，就是1.8的高电平，提示网络是关闭的。




------------------ 原始邮件 ------------------
发件人:&nbsp;"木林森"<595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月26日(星期三) 下午5:52
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



你好，我调试can过程中，执行candump命令，提示&nbsp;Address family not supported by protocol family.，是内核配置有问题吗，比如有模块未加载到。还有因为协议哪里对不上




------------------ 原始邮件 ------------------
发件人:&nbsp;"benfounder"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 下午4:20
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<Hi3559AV100_CAN@noreply.github.com&gt;;
抄送:&nbsp;"夏接建"<595284218@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)




Closed #1.

**Comment by diaosi-xia** [comment]
大佬你好，扩展帧 无法接收到数据，代码只支持标准帧吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "夏接建"                                                                                    <595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 下午4:49
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



can 收发数据都正常了，是主板电路有点问题，谢谢大佬




------------------ 原始邮件 ------------------
发件人:&nbsp;"木林森"<595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月27日(星期四) 下午4:00
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



内核了配置了下，没有报这个错了。但是现在cansend命令发送数据后就打印 interface=can1&nbsp; family=29,type=3,protol=1,然后是write&nbsp; network is down. 。我用示波器量没有数据波形，就是1.8的高电平，提示网络是关闭的。




------------------ 原始邮件 ------------------
发件人:&nbsp;"木林森"<595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月26日(星期三) 下午5:52
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



你好，我调试can过程中，执行candump命令，提示&nbsp;Address family not supported by protocol family.，是内核配置有问题吗，比如有模块未加载到。还有因为协议哪里对不上




------------------ 原始邮件 ------------------
发件人:&nbsp;"benfounder"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 下午4:20
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<Hi3559AV100_CAN@noreply.github.com&gt;;
抄送:&nbsp;"夏接建"<595284218@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)




Closed #1.

**Comment by diaosi-xia** [comment]
大佬&nbsp; 初始化时候只初始化了std_recv_map，标准帧。接收时只能2选1吗，要么标准帧要么扩展帧？测试扩展帧接收不行的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "夏接建"                                                                                    <595284218@qq.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 下午3:32
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



大佬你好，扩展帧 无法接收到数据，代码只支持标准帧吗




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "夏接建"                                                                                    <595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 下午4:49
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



can 收发数据都正常了，是主板电路有点问题，谢谢大佬




------------------ 原始邮件 ------------------
发件人:&nbsp;"木林森"<595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月27日(星期四) 下午4:00
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



内核了配置了下，没有报这个错了。但是现在cansend命令发送数据后就打印 interface=can1&nbsp; family=29,type=3,protol=1,然后是write&nbsp; network is down. 。我用示波器量没有数据波形，就是1.8的高电平，提示网络是关闭的。




------------------ 原始邮件 ------------------
发件人:&nbsp;"木林森"<595284218@qq.com&gt;;
发送时间:&nbsp;2020年2月26日(星期三) 下午5:52
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)



你好，我调试can过程中，执行candump命令，提示&nbsp;Address family not supported by protocol family.，是内核配置有问题吗，比如有模块未加载到。还有因为协议哪里对不上




------------------ 原始邮件 ------------------
发件人:&nbsp;"benfounder"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 下午4:20
收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<Hi3559AV100_CAN@noreply.github.com&gt;;
抄送:&nbsp;"夏接建"<595284218@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1)




Closed #1.

**Comment by tisyang** [comment]
> 大佬&nbsp; 初始化时候只初始化了std_recv_map，标准帧。接收时只能2选1吗，要么标准帧要么扩展帧？测试扩展帧接收不行的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "夏接建" <595284218@qq.com&gt;; 发送时间:&nbsp;2020年8月20日(星期四) 下午3:32 收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;; 主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1) 大佬你好，扩展帧 无法接收到数据，代码只支持标准帧吗
> ------------------ 原始邮件 ------------------ 发件人: "夏接建" <595284218@qq.com&gt;; 发送时间:&nbsp;2020年2月28日(星期五) 下午4:49 收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;; 主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1) can 收发数据都正常了，是主板电路有点问题，谢谢大佬
> ------------------ 原始邮件 ------------------ 发件人:&nbsp;"木林森"<595284218@qq.com&gt;; 发送时间:&nbsp;2020年2月27日(星期四) 下午4:00 收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;; 主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1) 内核了配置了下，没有报这个错了。但是现在cansend命令发送数据后就打印 interface=can1&nbsp; family=29,type=3,protol=1,然后是write&nbsp; network is down. 。我用示波器量没有数据波形，就是1.8的高电平，提示网络是关闭的。
> ------------------ 原始邮件 ------------------ 发件人:&nbsp;"木林森"<595284218@qq.com&gt;; 发送时间:&nbsp;2020年2月26日(星期三) 下午5:52 收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<reply@reply.github.com&gt;; 主题:&nbsp;回复： [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1) 你好，我调试can过程中，执行candump命令，提示&nbsp;Address family not supported by protocol family.，是内核配置有问题吗，比如有模块未加载到。还有因为协议哪里对不上
> ------------------ 原始邮件 ------------------ 发件人:&nbsp;"benfounder"<notifications@github.com&gt;; 发送时间:&nbsp;2019年10月30日(星期三) 下午4:20 收件人:&nbsp;"benfounder/Hi3559AV100_CAN"<Hi3559AV100_CAN@noreply.github.com&gt;; 抄送:&nbsp;"夏接建"<595284218@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [benfounder/Hi3559AV100_CAN] 驱动与dts匹配 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
请问，接收 >=400 ID 的问题搞定了吗？

**Comment by xujunwen1993** [comment]
大佬，引入你的驱动后，主soc下的CAN测试没问题，但是测试sensor Hub上的CAN，我用外部CAN测试工具无法检查到sensorHub CAN的波特率，将sensorHub CAN与主soc下的CAN直连也无法检查，请问sensor Hub下的CAN还需要设置其他吗？

**Comment by xujunwen1993** [comment]
大佬，我又仔细阅读你的驱动，发现你默认把CAN的时钟设定在50M(priv->can.clock.freq = 50000000;)，但是在sensorHub上，默认频率是24M，所以最后实际的出来的波特率少了大约一半，后面又通读了海思的用户手册，描述CAN支持50M,但是遗憾的是在senserHub_can的时钟配置寄存器，只有复位的描述，其余31位全部保留，所以我暂时在设备树中加时钟字段，来区分使用50M或24M解决波特率不对的情况
