### ISSUE TITLE
驱动异常

### ISSUE THREAD

**Issue by LiJunJie27** [benfounder/Hi3559AV100_CAN#2]
大佬 您好。我在打完您提供的补丁后，用ip命令打开can口，查看can口信息出现如下问题：

3: can1: <NOARP,UP,LOWER_UP,ECHO> mtu 16 qdisc pfifo_fast state UNKNOWN qlen 10
    link/can
    can state STOPPED (berr-counter tx 0 rx 0) restart-ms 0
    bitrate 500000 sample-point 0.850
    tq 100 prop-seg 8 phase-seg1 8 phase-seg2 3 sjw 1
    hi3559av100_can: tseg1 1..16 tseg2 1..8 sjw 1..4 brp 1..64 brp-inc 1
    clock 50000000

can state处于STOPPED状态，而不是调试时常见的can state ERROR-ACTIVE状态。不知您是否遇到过。您的SW2拨码开关是如何设置的。

**Comment by benfounder** [comment]
pinmux 设置了么？使用 himm 0x1F0000DC 0x1102 ， himm 0x1F0000E0 0x1102

LiJunJie27 <notifications@github.com> 于 2020年7月22日周三 下午1:59写道：

**Comment by LiJunJie27** [comment]
您好，我在设置复用管脚之后任然存在上述can state STOPPED的问题。您那边是有还有其他需要排查的内容。

**Comment by benfounder** [comment]
ip的命令行贴上来看看。

LiJunJie27 <notifications@github.com> 于2020年8月3日周一 上午9:03写道：

**Comment by LiJunJie27** [comment]
大佬您好 问题已经解决，是can盒硬件问题，多谢指点
